stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - sh /home/root/bobby/build_back.sh

test:
  stage: test
  before_script:
    - sudo systemctl start bobby-test
  script:
    - sh /home/root/bobby/test_back.sh
  after_script:
    - sudo systemctl stop bobby-test

deploy:
  only:
    - master
  stage: deploy
  script:
    - sudo sh /home/root/bobby/deploy_back.sh