stages:
  - build
  - test
  - deploy-prod

build:
  script:
    - gradle build
    - ls build/libs
    - mv build/libs/big-bobbys-restaurant-backend-1.0.0.jar /tmp

test:
  before_script:
    - sudo systemctl start bobby-test
    - bash /home/root/bobby/wait_for_test_up.sh
  script:
    - newman run test/bigbobby_tests.postman_collection.json
  after_script:
    - sudo systemctl stop bobby-test

deploy-prod:
  only:
    - master
  before_script:
    - sudo systemctl stop bobby-prod
    - sudo bash /home/root/bobby/move_to_prod.sh
  script:
    - sudo systemctl start bobby-prod
    - bash /home/root/bobby/wait_for_prod_up.sh