stages:
  - build
  - test

build:
  script:
    - gradle build
    - ls build/libs
    - mv build/libs/big-bobbys-restaurant-backend-1.0.0.jar /tmp

test:
  before_script:
    - systemctl start bobby-test
    - bash /tmp/wait_for_test_up.sh
  script:
    - newman run /tmp/bigbobby_tests.postman_collection.json
  after_script:
    - systemctl stop bobby-test